# Pipefish Adult Euthanasia {#sec-husbandry_adult_syng_euth}

## Introduction

-   **Purpose**: This procedure describes best practices for euthanizing adult pipefish.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey\
-   **Date Created**: February 29, 2024

## Materials

-   Container to hold fish while being euthanized.
-   Post mortem fixing equipment
-   Morgue

## Solutions

::: {.callout-note title="Note"}
Tricaine must be pharmaceutical-grade. We use tricaine purchased from Pentair, manufactured by Western Chemical and FDA approved. Tricaine (3-amino benzoic acid ethyl lester also called ethyl m-aminoboenzoate) comes in a powdered form. Purchase the smallest amount possible because tricaine expires quickly.
:::

-   Euthanasia strength Mesab (see below and @sec-general_recipe_mesab)

-   **Mesab Stock Solution (4g/L From Zebrafish Book 4th edition) (tris buffered)**:

    -   4 g tricaine powder
    -   979 ml DD water
    -   \~21 ml 1 M Tris (pH 9).
    -   Adjust pH to \~7.
    -   Aliquot in 50ml tubes, label with MESAB Stock Solution 4g/L, and store in a -20 freezer.
    -   This makes 1 liter of solution.

-   **Euthanasia Solution (300 mg/L)**:

    -   Make a solution of tris buffered **Stock Solution** as described above. (Or obtain an aliquot from the freezer)
    -   Make a solution of 3.0 ppt Instant Ocean by adding 0.3 grams of Instant Ocean to 100 ml of DD water.
    -   Combine 7.5ml of stock solution into 100 ml of 3 ppt Instant Ocean.
    -   Store solution in an amber bottle to protect it from light and add mixed and expiration dates (6 months after being mixed) to the bottle.

## Procedure

1.  Place fish in euthanasia strength mesab and wait 10 minutes.
2.  To confirm death wait ten minutes after opercular movement has stopped and perform a tap test. TO do this gently tap on the table next to the container holding the fish. If the fish is still alive this will trigger a startle response, wait 5 more minutes and repeat tap test. If no response, proceed to fixing for post mortem experiments or place fish in the morgue.

::: {.callout-note title="IACUC Protocol"}
This procedure is covered under the University of Oregon IACUC protocol for fish euthanasia. Euthanasia must be performed using approved methods and only by trained personnel. Always follow approved protocols for animal welfare.
:::

## Related Protocols

-   @sec-general_recipe_mesab - Mesab stock solution recipe
-   @sec-husbandry-pipefish_larval_euth - Pipefish embryo and larval euthanasia
-   @sec-husbandry-fish_health_check - Daily health checks
