# Room Light Programming {#sec-husbandry-room_lighting}

## Introduction

-   **Purpose**: This procedure describes how to set and or change the lighting regime in 310 A,B,C.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Threespine stickleback, (*Gasterosteus aculeatus*)
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey
-   **Date Created**: 2008

::: {.callout-note title="Note"}
To check if the lighting is programmed correctly use a data logger to track the light levels over the course of at least 24 hours.
:::

## Materials

2.  Older PC located in the closet outside the animal facility.
3.  Liason software and manual.

## Procedure

### Standard approach

-   Programming of fish room lighting regimes is done using the wall unit Grafik Eye 3000 and a PC.
-   The unit is programmed in terms of scenes.
-   Each scene specifies a lighting event, e.g. turning on the lights in one room over a 1/2 hour time period.
-   Scenes are set at the control unit following the directions in the manual.
-   Four scenes have been set up to turn off or on lighting in the main room and the breeding room.

Scene 1: **Main room ON** with 30 min dawn.\
\
Scene 2: **Main room OFF** with 30 min dusk.\
\
Scene 3: **Breeding room ON** with 30 min dawn.\
\
Scene 4: **Breeding room OFF** with 30 min dusk.

-   Once the scenes are programmed you must tell the unit when to activate the scenes.
-   This is done with a PC and Grafik Eye Liason software.
-   If the software needs to be installed do so.
-   Connect the PC to the control unit.

In EDIT MODE,

1.  Select control unit (I think that this unit is GRX3105).
2.  Go to schedule (Not program).
3.  Drag scenes (upper right box) to desired times.
4.  Drag control unit (lower right box) to each scene.
5.  Be sure and copy schedule to the weekend.
6.  Go to FILE and establish communications via Online Options.
7.  After communications have been established go back to edit mode.
8.  Go to Online Options and select transfer data. This should program the wall unit when to activate scenes.

### Alternate Version:

1.  Open program located on PC desktop
2.  Select create or edit
3.  Under file and select sticklePAC310.LIA and OPEN
4.  Under Online options select ESTABLISH COMMUNICATIONS
5.  Under timeclock select SCHEDULE EVENTS
6.  Drag scenes (upper right box) to desired times
7.  Drag control unit (lower right box) to each scene
8.  Be sure and copy schedule to the weekend
9.  Go to FILE and establish communications via Online Options.
10. After communications have been established go back to edit mode
11. Go to Online Options and select transfer data. This should program the wall unit when to activate scenes.

## Related Protocols

-   @sec-husbandry-stickle_density - Stickleback density standards (includes lighting requirements)
-   @sec-husbandry-incubator_use - Incubator use for embryos
