# Pipefish Embryo & Larval Euthanasia {#sec-husbandry-pipefish_larval_euth}

## Introduction

-   **Purpose**: This procedure describes best practices for euthanizing embryonic and larval pipefish.
-   **Procedure Type**: Husbandry
-   **Species**:
    -   Bay pipefish, (*Syngnathus leptorhyncus*)
    -   Gulf pipefish (*Syngnathus scovelli*)
-   **Author**: Mark Currey
-   **Date Created**: 2023

## Materials

-   Euthanasia strength Mesab (see below)
-   Container to hold fish while being euthanized
-   Post mortem fixing equipment
-   Morgue

## Solutions

::: {.callout-note title="Note"}
Tricaine must be pharmaceutical-grade. We use tricaine purchased from Pentair, manufactured by Western Chemical and FDA approved. Tricaine (3-amino benzoic acid ethyl lester also called ethyl m-aminoboenzoate) comes in a powdered form. Purchase the smallest amount possible because tricaine expires quickly.
:::

::: {.callout-caution title="Safety"}
When handling Mesab please wear gloves and wash your hands after use.
:::

-   **Mesab Stock Solution (4g/L, From Zebrafish Book 4th edition) (tris buffered)**:

    -   4 g tricaine powder
    -   979 ml DD water
    -   \~21 ml 1 M Tris (pH 9)
    -   Adjust pH to \~7
    -   Aliquot in 50ml tubes, label with MESAB Stock Solution 4g/L, and store in a -20 freezer
    -   This makes 1 liter of solution

-   **Euthanasia Solution (300 mg/L)**:

    -   Make a solution of tris buffered **Stock Solution** as described above. (Or obtain an aliquot from the freezer)
    -   Combine 7.5ml of stock solution into 100 ml of fish water

## Procedure

1.  Procedure for embryo euthanasia:

    1.  Place embryos into a MS-222 euthanasia solution.
    2.  Leave embryos in solution until movement has stopped, \~ 10 minutes.
    3.  If fish is to be used for experiments, proceed with fixation or preparation for the experiment.
    4.  If the fish are to be disposed of, place embryo in 95% ETOH for 5 minutes and then into morgue for disposal.

::: {.callout-note title="Note"}
This step is necessary as a startle response is not obvious in unhatched fish.
:::

2.  Procedure for larval euthanasia:

    1.  Place larva into a MS-222 euthanasia solution.
    2.  Wait 10 minutes and perform a tap test to look for a startle response. If there is a response wait 5 minutes and repeat startle response test. Repeat this step every 5 minutes as needed. If there is no response move to fixing for post mortem experiments or place in morgue.

::: {.callout-note title="IACUC Protocol"}
This procedure is covered under the University of Oregon IACUC protocol for fish euthanasia. Euthanasia must be performed using approved methods and only by trained personnel. Always follow approved protocols for animal welfare.
:::

## Related Protocols

-   @sec-husbandry_adult_syng_euth - Adult pipefish euthanasia
-   @sec-general_recipe_mesab - Mesab stock solution recipe
-   @sec-husbandry_syng_cross - Pipefish crossing and breeding
